# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Crisper
spec:
  description: Crisper application with Ollama MCP Bridge backend
  variables:
    - key: PUBLIC_DOMAIN
      type: DOMAIN
      name: Domain
      description: Domain for the Crisper backend
    - key: JWT_SECRET
      type: STRING
      name: JWT Secret
      description: Secret key for JWT authentication
    - key: OLLAMA_URL
      type: STRING
      name: Ollama URL
      description: URL of the Ollama server
    - key: OLLAMA_MODEL
      type: STRING
      name: Ollama Model
      description: Ollama model to use (e.g., qwen2.5:0.5b)
  tags:
    - AI
    - Tool
  services:
    - name: ollama-mcp-bridge
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/python.svg
      template: PREBUILT
      spec:
        source:
          image: python:3.11-slim
        command:
          - sh
          - -c
          - "pip install ollama-mcp-bridge && ollama-mcp-bridge --config /app/mcp-config.json --host 0.0.0.0 --port 8000 --ollama-url ${OLLAMA_URL}"
        ports:
          - id: http
            port: 8000
            type: HTTP
        env:
          OLLAMA_URL:
            default: "https://ollama.crisper.skills.eliaschen.dev"
        configs:
          - path: /app/mcp-config.json
            template: |
              {}

    - name: backend
      icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/nodejs.svg
      template: GIT
      spec:
        source:
          repoURL: https://github.com/YOUR_USERNAME/crisper
          branch: main
          submodule: backend
        ports:
          - id: http
            port: 3000
            type: HTTP
        env:
          NODE_ENV:
            default: "production"
          JWT_SECRET:
            default: "${JWT_SECRET}"
          OLLAMA_BRIDGE:
            default: "http://ollama-mcp-bridge.zeabur.internal:8000"
          OLLAMA_MODEL:
            default: "${OLLAMA_MODEL}"
          SQLITE_PATH:
            default: "sqlite.db"
        domainKey: PUBLIC_DOMAIN
      dependencies:
        - ollama-mcp-bridge
